# Numpy 

In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3,4]) # simple creating of a numpy array
x
print(type(x)) # Check the data type of array 

<class 'numpy.ndarray'>


# Dimensions in Arrays


In [3]:
x.ndim # Check the dimension of array

1

In [4]:
ar2=np.array([[1,2,3,4],[5,6,7,8]]) # Creating a 2D array
ar2
ar2.ndim # Check the dimension of array

2

In [5]:
ar3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]) # Creating a 3D array
print(ar3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [6]:
# Create a numpy array with 6 dimensions
arn = np.array([1, 2, 3, 4], ndmin=6)
arn
arn.ndim  # Check the dimension of the array


6

# creating arrays using numpy fuctions

# Zeros

In [7]:
ar_zero = np.zeros(3)
ar_zero

array([0., 0., 0.])

In [8]:
ar_zeros = np.zeros((2, 3))  # Create a 2D array of zeros
ar_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [9]:
ar_ones = np.ones(3)
ar_ones

array([1., 1., 1.])

In [10]:
ar_ones = np.ones((3,5))
ar_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# ARange

In [11]:
ar_range = np.arange(10) # Create a 1D array with values from 0 to 9
ar_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ar_range=np.arange(2,5,) 
ar_range

array([2, 3, 4])

In [13]:
ar_range=np.arange(1,10,2) # Create a 1D array with values from 1 to 9 with step size of 2
ar_range

array([1, 3, 5, 7, 9])

In [14]:
arr_range=np.arange(1,14,3) # Create a 1D array with values from 1 to 9 with step size of 3
arr_range

array([ 1,  4,  7, 10, 13])

# Diagonal

In [15]:
ar_dia=np.eye(3) # Create a 2D identity matrix of size 3x3
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
ar_dia=np.eye(3,4) # Create a 2D identity matrix of size 3x4
ar_dia

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# linspace

In [17]:
# linspace ko hum equally spaced numbers generate krne ke liye use krte hain
ar_linspace = np.linspace(0, 10, num=5)
ar_linspace 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Genrating Random numbers using Rand function

# 01_Rand

In [18]:
rn=np.random.rand(10)
rn
# ye random numbers hain 0 se 1 ke beech
# ager hum dobarah run krenge to different random numbers milenge


array([0.91359817, 0.56495381, 0.88418563, 0.52307312, 0.19065434,
       0.07336068, 0.7085033 , 0.97591096, 0.03657908, 0.16343026])

In [19]:
rn=np.random.rand(3,4,2)
rn
# ye 3 rows aur 4 columns ka matrix hai
# or ye 2 dimensional array hai

array([[[0.32648301, 0.12892954],
        [0.48299474, 0.07528335],
        [0.83451861, 0.06818518],
        [0.18359729, 0.38809784]],

       [[0.58789703, 0.23805056],
        [0.38702274, 0.16637249],
        [0.72043539, 0.62133012],
        [0.81429618, 0.94471381]],

       [[0.45856005, 0.48203562],
        [0.28914099, 0.63989158],
        [0.69689469, 0.62011547],
        [0.51210688, 0.46213844]]])

# 

In [20]:
# #Array shape ka matlab

# numpy me jab tu shape = (a, b, c) dekhta hai to iska matlab hota hai:

# a → kitne blocks / layers hain

# b → har block me kitni rows hain

# c → har row me kitne columns hain

# 02_Randn()

In [21]:
# isme just -ve values bi aa sakti hain
rn2=np.random.randn(4)
rn2

array([ 0.1658283 , -1.00936673, -0.58074335,  1.86947869])

In [22]:
rn2=np.random.randn(2,10,3)
rn2

array([[[ 0.54726415, -0.77156782, -2.09289274],
        [ 0.91643981,  1.05914897,  0.85264912],
        [-0.13610014, -0.18818393,  1.34710005],
        [ 0.38820237, -0.46179062,  0.54214917],
        [ 0.44313785,  1.11636724, -0.54976694],
        [-0.76987522, -0.47010483,  0.94802996],
        [ 0.64546337, -0.85558373, -0.67130318],
        [-0.79025661, -0.73065052,  1.16556017],
        [ 0.66974919, -0.45411253, -0.47658398],
        [ 0.75457873, -1.48668849, -1.14751209]],

       [[ 0.95333223,  0.00702638,  0.88282331],
        [ 0.6597173 ,  0.25879957,  0.47810556],
        [-0.36488914, -1.32635347,  0.8577433 ],
        [-0.17710247,  0.20119327, -0.59667247],
        [ 0.23562253, -0.81860504,  1.51306139],
        [ 1.32938158, -1.82656149, -1.54490528],
        [ 0.29170289, -0.50154467,  1.48842748],
        [-0.96077279,  0.49146811,  0.32505277],
        [ 0.08335754, -0.49860013,  0.92646984],
        [-0.71545376,  0.02682964,  0.86138897]]])

# 03_Ranf

In [23]:
rn3=np.random.rand(10)
# ye function 0 se 1 ke beech random numbers generate karta hai
rn3

array([0.27817107, 0.50388841, 0.75353699, 0.91637922, 0.88149533,
       0.95649913, 0.1469522 , 0.91965106, 0.3851518 , 0.43123904])

# 05_Randint


In [24]:
rn4=np.random.randint(1,10,5)
rn4
# iska matlab ha ke rn4 me 5 random integers honge jo 1 se 10 ke beech honge mtlab rn4=np.random.randint(min, max,total number)
# ye function 1 se 10 ke beech 5 random integers generate karega

array([4, 9, 6, 1, 9], dtype=int32)

In [25]:
# example
rn5=np.random.randint(1,100,110)
rn5
# hunm inki values se ziyada number bi genrate kar sakte hain

array([13, 75,  1,  1, 88, 36, 38, 84, 68,  6, 63, 42, 95, 87, 11, 27, 84,
        3, 25,  6, 42, 64, 87, 41, 76, 88, 84, 65, 39, 64, 97, 69, 69, 74,
       17, 36, 41, 33, 36, 47, 14, 83, 38, 55, 80, 65,  5, 58, 45, 62, 51,
       89, 30, 16, 13, 67, 44, 28, 42, 65,  6, 15, 55, 15, 67, 57, 44, 65,
       77, 27, 60, 25, 83, 82, 76, 89,  4,  8, 46, 16, 31, 15,  1,  1, 51,
       48, 19, 99, 90, 54, 31, 74,  5, 79, 94, 56, 24, 25, 37, 88,  2, 48,
       82, 68, 80, 99, 33, 10, 78, 84], dtype=int32)

In [28]:
print(int(eval(input("enter"))))

0
