# Numpy 

In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3,4]) # simple creating of a numpy array
x
print(type(x)) # Check the data type of array 

<class 'numpy.ndarray'>


# Dimensions in Arrays


In [3]:
x.ndim # Check the dimension of array

1

In [4]:
ar2=np.array([[1,2,3,4],[5,6,7,8]]) # Creating a 2D array
ar2
ar2.ndim # Check the dimension of array

2

In [5]:
ar3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]) # Creating a 3D array
print(ar3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [6]:
# Create a numpy array with 6 dimensions
arn = np.array([1, 2, 3, 4], ndmin=6)
arn
arn.ndim  # Check the dimension of the array


6

# creating arrays using numpy fuctions

# Zeros

In [7]:
ar_zero = np.zeros(3)
ar_zero

array([0., 0., 0.])

In [8]:
ar_zeros = np.zeros((2, 3))  # Create a 2D array of zeros
ar_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [9]:
ar_ones = np.ones(3)
ar_ones

array([1., 1., 1.])

In [10]:
ar_ones = np.ones((3,5))
ar_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# ARange

In [11]:
ar_range = np.arange(10) # Create a 1D array with values from 0 to 9
ar_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
ar_range=np.arange(2,5) 
ar_range

array([2, 3, 4])

In [13]:
ar_range=np.arange(1,10,2) # Create a 1D array with values from 1 to 9 with step size of 2dir


In [14]:
arr_range=np.arange(1,10,3) # Create a 1D array with values from 1 to 9 with step size of 3
arr_range

array([1, 4, 7])

# Diagonal

In [15]:
ar_dia=np.eye(3) # Create a 2D identity matrix of size 3x3
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
ar_dia=np.eye(3,4) # Create a 2D identity matrix of size 3x4
ar_dia

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# linspace

In [17]:
# linspace ko hum equally spaced numbers generate krne ke liye use krte hain
ar_linspace = np.linspace(0, 10, num=5)
ar_linspace 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Genrating Random numbers using Rand function

sdfs

In [ ]:
xzczc