# Numpy 

In [77]:
import numpy as np


In [78]:
x=np.array([1,2,3,4]) # simple creating of a numpy array
x
print(type(x)) # Check the data type of array 

<class 'numpy.ndarray'>


# Dimensions in Arrays


In [79]:
x.ndim # Check the dimension of array

1

In [80]:
ar2=np.array([[1,2,3,4],[5,6,7,8]]) # Creating a 2D array
ar2
ar2.ndim # Check the dimension of array

2

In [81]:
ar3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]) # Creating a 3D array
print(ar3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [82]:
# Create a numpy array with 6 dimensions
arn = np.array([1, 2, 3, 4], ndmin=6)
arn
arn.ndim  # Check the dimension of the array


6

# creating arrays using numpy fuctions

# Zeros

In [83]:
ar_zero = np.zeros(3)
ar_zero

array([0., 0., 0.])

In [84]:
ar_zeros = np.zeros((2, 3))  # Create a 2D array of zeros
ar_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

# Ones

In [85]:
ar_ones = np.ones(3)
ar_ones

array([1., 1., 1.])

In [86]:
ar_ones = np.ones((3,5))
ar_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# ARange

In [87]:
ar_range = np.arange(10) # Create a 1D array with values from 0 to 9
ar_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
ar_range=np.arange(2,5,) 
ar_range

array([2, 3, 4])

In [89]:
ar_range=np.arange(1,10,2) # Create a 1D array with values from 1 to 9 with step size of 2
ar_range

array([1, 3, 5, 7, 9])

In [105]:
arr_range=np.arange(1,14,3) # Create a 1D array with values from 1 to 9 with step size of 3
arr_range

array([ 1,  4,  7, 10, 13])

# Diagonal

In [91]:
ar_dia=np.eye(3) # Create a 2D identity matrix of size 3x3
ar_dia

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
ar_dia=np.eye(3,4) # Create a 2D identity matrix of size 3x4
ar_dia

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# linspace

In [93]:
# linspace ko hum equally spaced numbers generate krne ke liye use krte hain
ar_linspace = np.linspace(0, 10, num=5)
ar_linspace 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Genrating Random numbers using Rand function

# 01_Rand

In [94]:
rn=np.random.rand(10)
rn
# ye random numbers hain 0 se 1 ke beech
# ager hum dobarah run krenge to different random numbers milenge


array([0.22577807, 0.44717122, 0.6931476 , 0.50239284, 0.49019279,
       0.54468748, 0.73437291, 0.20520056, 0.42105625, 0.64433156])

In [116]:
rn=np.random.rand(3,4,2)
rn
# ye 3 rows aur 4 columns ka matrix hai
# or ye 2 dimensional array hai

array([[[0.18063435, 0.4978976 ],
        [0.68825126, 0.50469996],
        [0.64321486, 0.15439551],
        [0.0932253 , 0.63153654]],

       [[0.63202796, 0.91575439],
        [0.67184874, 0.20873344],
        [0.80579225, 0.59403514],
        [0.21160284, 0.63849634]],

       [[0.84411426, 0.82057032],
        [0.81594287, 0.57374858],
        [0.94715357, 0.72200114],
        [0.6117002 , 0.69101766]]])

# 

In [117]:
# #Array shape ka matlab

# numpy me jab tu shape = (a, b, c) dekhta hai to iska matlab hota hai:

# a → kitne blocks / layers hain

# b → har block me kitni rows hain

# c → har row me kitne columns hain

# 02_Randn()

In [121]:
# isme just -ve values bi aa sakti hain
rn2=np.random.randn(4)
rn2

array([-0.55626777,  0.34947602, -0.30647052, -1.9956696 ])

In [113]:
rn2=np.random.randn(2,10,3)
rn2

array([[[-0.76682024,  1.64003161,  0.89988776],
        [-0.90775247,  0.34381729,  0.14908867],
        [-0.33749306,  2.06226076,  0.88465215],
        [ 0.74438869,  0.86204508, -1.00021508],
        [-1.85141914,  1.09529376, -1.30484036],
        [ 2.80939057, -0.14182903,  0.01860199],
        [-2.42216837,  1.04375674, -0.12149832],
        [ 0.30878311, -1.65810833,  0.15594016],
        [ 0.14255367, -0.42036763,  0.79175984],
        [-0.30477675,  0.58688561,  0.02043153]],

       [[-0.83446406,  0.45691422, -0.83642462],
        [ 0.89254951, -1.65758442, -1.11201777],
        [-0.08251307,  0.68274865, -0.19367348],
        [ 0.18614065, -0.13350818, -0.40971598],
        [ 0.0216165 , -0.60207895, -0.14564691],
        [-0.39708024, -0.98448856,  0.01753851],
        [-0.37044491, -0.09095285,  0.15657549],
        [ 0.76621162, -0.0634075 ,  2.79796337],
        [ 1.43495386,  0.05331509, -0.63271894],
        [-1.43435398,  0.44353069,  0.61696863]]])

# 03_Ranf

In [125]:
rn3=np.random.rand(10)
# ye function 0 se 1 ke beech random numbers generate karta hai
rn3

array([0.08708246, 0.10919338, 0.22757396, 0.61403107, 0.95451988,
       0.35839883, 0.47456449, 0.99869034, 0.43244034, 0.77293132])

# 05_Randint


In [134]:
rn4=np.random.randint(1,10,5)
rn4
# iska matlab ha ke rn4 me 5 random integers honge jo 1 se 10 ke beech honge mtlab rn4=np.random.randint(min, max,total number)
# ye function 1 se 10 ke beech 5 random integers generate karega

array([2, 8, 6, 4, 5], dtype=int32)

In [140]:
# example
rn5=np.random.randint(1,100,110)
rn5
# hunm inki values se ziyada number bi genrate kar sakte hain

array([16,  7, 75, 27, 69, 39, 62, 16, 44, 99, 38, 18, 24, 12, 22, 68, 66,
        2, 85,  8, 16, 36, 44, 94, 78, 30, 95, 51, 71, 80, 52, 32, 92, 91,
       89, 28, 12, 23, 15, 15, 59, 99, 93, 84, 31, 25,  1, 78, 90, 11, 50,
       78, 28, 39, 31, 38, 20,  5, 53, 68, 69,  5, 60, 33, 16, 93, 10, 37,
        8, 73, 85, 35, 84, 36, 59, 33, 14, 84, 82, 73, 17, 59, 63, 43, 94,
       88, 25, 65, 68, 91,  7, 70, 91, 54, 64, 28, 99,  3, 92, 29, 87, 15,
       59,  7, 91,  2, 15, 14, 67, 35], dtype=int32)